# Generated by Django 5.0.2 on 2024-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
