# Generated by Django 5.0.2 on 2024-03-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='timestamp_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
