quarkus.application.name=quarkus-backend

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${HALMA_DB_USER}
quarkus.datasource.password=${HALMA_DB_PASSWORD}
quarkus.datasource.jdbc.url=${HALMA_DB_URL}