quarkus.application.name=quarkus-backend

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${HALMA_DB_USER}
quarkus.datasource.password=${HALMA_DB_PASSWORD}
quarkus.datasource.jdbc.url=${HALMA_DB_URL}


quarkus.liquibase.clean-at-start=true
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=classpath:db/migration/changeLog.xml

# Maybe one day useful
#quarkus.hibernate-orm.physical-naming-strategy=com.itdobler.oss.halma.quarkus.LiquibaseQuarkusCompatiblePhysicalNamingStrategy